### ISSUE TITLE
cant encrypt

### ISSUE THREAD

**Issue by evan6800** [odwdinc/SSBU_Amiibo#21]
i made one amiibo just fine but now im trying to make a second but whenever i try to encrypt it and save it the file doesn't show up. even when i search it doesn't show up.
it saves the new version as a .bind file but when i go to encrypt it doesnt show up
it doent seem to be updating the file when i hit save either

**Comment by odwdinc** [comment]
It will not save if there are problems with the build/mods you are trying. 
Kind of a check if its going to be accepted by the game or not.
You cant have more then 3 slots filled. aka (1 x 1 slot +  1 x 2 slot) , ( 1 x 3 slot), (3 x 1 slot)

Otherwise attach some more info to the bug and I will look it over.
